# Generated by Django 3.1.7 on 2021-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
